apiVersion: v1
kind: Secret
metadata:
  name: novax-secret
  namespace: novax
type: Opaque
data:
  mysql-username: cm9vdA==  # base64 encoded 'root'
  mysql-password: cGFzc3dvcmQ=  # base64 encoded 'password'
  redis-password: cGFzc3dvcmQ=  # base64 encoded 'password'
